# Generated by Django 2.0.5 on 2019-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=64)),
                ('usertype', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('factory', models.CharField(max_length=60)),
            ],
        ),
    ]
